def CONTAINER_NAME="politiesysteem"
def CONTAINER_TAG="latest"

node {
    git url: 'https://github.com/S62Groep4/PolitieSysteem.git'

    stage('Initialize'){
        def dockerHome = tool 'Docker'
        def mavenHome  = tool 'Maven3'
        env.PATH = "${dockerHome}/bin:${mavenHome}/bin:${env.PATH}"
    }

    stage('Checkout') {
        checkout scm
    }

    stage('Build'){
        sh "mvn -f Java_Backend/pom.xml clean install"
    }

    stage('Sonar'){
        try {
            sh "mvn -f Java_Backend/pom.xml sonar:sonar"
        } catch(error){
            echo "The sonar server could not be reached ${error}"
        }
    }
	
    stage('Artifactory'){
        def server = Artifactory.server 'Artifactory'

        rtMaven = Artifactory.newMavenBuild()
	rtMaven.tool = 'Maven3' // Tool name from Jenkins configuration
	rtMaven.deployer releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local', server: server
	rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server: server
	rtMaven.deployer.deployArtifacts = true

	buildInfo = Artifactory.newBuildInfo()
	rtMaven.run pom: 'Java_Backend/pom.xml', goals: 'clean install', buildInfo: buildInfo
	rtMaven.deployer.deployArtifacts buildInfo
	server.publishBuildInfo buildInfo
    }

    stage('Docker-compose'){
		try {
            sh "sudo docker-compose down"
        }catch(error){}
        try {
            sh "sudo docker-compose down"
        }catch(error){}
        try {
            sh "sudo docker-compose up -d"
        }catch(error){}
    }

    stage('Deploy'){
        sh 'mvn glassfish:deploy'
        input message: 'Please check if the application is deployed successfully'
    }
}
